select * from phim
select * from loai_ghe
select * from phong
select * from ghe
select * from lich_chieu
select * from nhan_vien
select * from khach_hang
select * from san_pham
select * from hoa_don
select * from ve
select * from chi_tiet_hoa_don